version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
    build:
        executor:
            name: win/default
            shell: bash.exe
        steps:
            - checkout

            - run:
                name: install dependencies
                command: | 
                    pip install -r requirements.txt
                    pipenv install
            
            - run:
                command: |
                print("Hello")
                #pipenv run python BreaktimeWatch/BreaktimeWatch_GUI.py test