version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
    build:
        executor:
            name: win/default
            shell: bash.exe
        steps:
            - checkout

            - run:
                name: install dependencies
                command: | 
                    pip install -r requirements.txt
                    pipenv install
            
           
            - run: echo 'Hello, Windows'

            - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
                path: test-results
            - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
                path: test-results
                destination: tr1              